### ISSUE TITLE
Интерфейс

### ISSUE THREAD

**Issue by romansilivestrov** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#11]
[Интерактивные элементы](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.9)
![image](https://user-images.githubusercontent.com/85496220/122046948-37f76900-cde8-11eb-9c29-93d0f4ad2e95.png)
![image](https://user-images.githubusercontent.com/85496220/122046963-3cbc1d00-cde8-11eb-83fa-9f542fa1f526.png)

А вот Rate button не является интерактивным элементом, но курсор почему-то pointer.
![image](https://user-images.githubusercontent.com/85496220/122046316-6f194a80-cde7-11eb-85bc-33ec44519d4c.png)

Subscription field - это всё же [форма](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.17).
![image](https://user-images.githubusercontent.com/85496220/122047477-e00d3200-cde8-11eb-8860-055a6cc55936.png)

На какую страницу я попаду при клике? :)
![image](https://user-images.githubusercontent.com/85496220/122048766-5cecdb80-cdea-11eb-92a8-9a7ef0bf3bc1.png)

Тут вроде как кнопки должны быть?
![image](https://user-images.githubusercontent.com/85496220/122049277-eb615d00-cdea-11eb-9b8a-82d06597d001.png)

При нажатии на кнопку лайка хорошо бы менять циферку. По крайней мере во всех проектах, что я видел это было реализовано.
![image](https://user-images.githubusercontent.com/85496220/122046634-d505d200-cde7-11eb-8aa5-70114e21792c.png)

Предполагается что masked text field позволяет вводить только определённые значения, в нашем случае дату в формате `ДД.ММ.ГГГГ`. При этом он автоматически должен расставлять точки и либо не позволять вводить некорректную дату (например 32.01.2021), либо сообщать пользователю о некорректном значенни.
![image](https://user-images.githubusercontent.com/85496220/122049715-67f43b80-cdeb-11eb-8485-cf51f26cd4c4.png)

В карточке комнаты должна быть ссылка, чтобы можно было эту самую комнату (room details) посмотреть.
![image](https://user-images.githubusercontent.com/85496220/122051526-5e6bd300-cded-11eb-8f49-679672e4b3ef.png)

**Comment by misha-yakubchuk** [comment]
Тут закончил.

**Comment by romansilivestrov** [comment]
### Datepicker

В отличие от dropdown не закрывается при клике на "применить". У текущей даты при попадании в диапазон сбивается `border-radius`.

![image](https://user-images.githubusercontent.com/85496220/122508260-5a68cc80-d00a-11eb-9ee1-4e695a295071.png)

**Comment by romansilivestrov** [comment]
### Content overflow

Текст может наезжать на иконку кнопки

![image](https://user-images.githubusercontent.com/85496220/122509936-58ecd380-d00d-11eb-8a5c-5a0af8903c5e.png)

Текст выходит за элемент

![image](https://user-images.githubusercontent.com/85496220/122510223-e3cdce00-d00d-11eb-8ed5-93f5f3caceef.png)
