### ISSUE TITLE
pug

### ISSUE THREAD

**Issue by romansilivestrov** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#12]
### Pagination

1. Пагинация - это интерактивный элемент, набор ссылок.
2. При этом для ![image](https://user-images.githubusercontent.com/85496220/122101737-588de600-ce1d-11eb-9400-594dd5a0bf4a.png) и ![image](https://user-images.githubusercontent.com/85496220/122101782-62afe480-ce1d-11eb-8326-f5c98bcf6abe.png) желательно создать либо отдельные элементы, либо обособить модификатором (например, `pagination__item_type_link`, `&_type_dots`, `&_type_button`).
3. Элемент `pagination__caption` согласно БЭМ должен находиться в родительском блоке.

### Conditional classes

![image](https://user-images.githubusercontent.com/85496220/122102683-5d9f6500-ce1e-11eb-9571-88001f957615.png)

В подобных местах можно использовать [ternary operator](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Conditional_Operator), получится:

```pug
- const expandedMod = isExpanded ? "_expanded" : "";
```

А ещё есть [логическое И](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND), с ним вообще необходимость в переменной отпадает:

```pug
input.dropdown__input(class=isExpanded && "dropdown__input_expanded")
```

### Defaults

![image](https://user-images.githubusercontent.com/85496220/122106122-33e83d00-ce22-11eb-84ca-fcbfc92c4453.png)

Константы с данными по умолчанию стоит вынести в `json`. Импортируется через `require`.

### Whitespace

![image](https://user-images.githubusercontent.com/85496220/122107745-12885080-ce24-11eb-844b-afd93ef2f2e7.png)

js в pug должен соответствовать [стайл](https://github.com/airbnb/javascript#whitespace--infix-ops) [гайду](https://github.com/airbnb/javascript#whitespace--in-braces).

А атрибуты - как в html (перед `nameForms` пробел лишний):
![image](https://user-images.githubusercontent.com/85496220/122108793-4dd74f00-ce25-11eb-81be-aa3eac890d33.png)

### Inputs

![image](https://user-images.githubusercontent.com/85496220/122111255-2f268780-ce28-11eb-96ab-39236301ca7a.png)
У инпутов отсутствует атрибут `type`, проверь миксин.

**Comment by romansilivestrov** [comment]
Здесь для списка стоит использовать семантические тэги.

![image](https://user-images.githubusercontent.com/85496220/122509260-22fb1f80-d00c-11eb-9d8a-69a111fb1660.png)

**Comment by misha-yakubchuk** [comment]
1) **Defaults**
Занятно конечно получается) Когда я только делал проект, объявлял переменные в файле, где они используются (как сейчас). Затем ближе к концу подумал о том, что было бы здорово хранить все подобные переменные в одном файле и сделал файл variables.pug, куда и вынес все константы. Затем на предревью мне сделали вот такое замечание: 
![image](https://user-images.githubusercontent.com/47563274/122547204-784d2600-d038-11eb-891d-0a5c0f9670e5.png)
и я вернул всё как было, каждая переменная в месте использования. Как быть?) Как по мне оба подхода имеют право на существование, у каждого есть плюсы и минусы. Я даже как-то принимал участие в обсуждении этой темы в чатике 2-го задания. Впрочем, решать ревьюеру, то есть тебе) 
2) **Inputs**
Да, я на предревью менял компонент `text-field` и не доглядел. Пофиксил при исправлении соседнего ишью 74e1b92ef83b89015f7e1c7e7010442e63f3b70a. Но я обратил внимание, что `type="text"` отображается только при запуске скрипта `start`. При `build`, `type="text"` пропадает, как буд-то webpack оптимизирует. При этом все значения type отличные от text на месте.

**Comment by romansilivestrov** [comment]
>и я вернул всё как было, каждая переменная в месте использования. Как быть?) Как по мне оба подхода имеют право на существование, у каждого есть плюсы и минусы. Я даже как-то принимал участие в обсуждении этой темы в чатике 2-го задания. Впрочем, решать ревьюеру, то есть тебе)

Эти подходы можно скомбинировать. То есть файл с константами создаёшь в папке текущего миксина. И искать не надо, и миксин не захламляет.

**Comment by romansilivestrov** [comment]
### button.pug

![image](https://user-images.githubusercontent.com/85496220/123504408-cd54f180-d661-11eb-9179-7c1a4938e376.png)

Здесь точно нужна запятая?)

И строки лучше объединять через [template string](https://github.com/airbnb/javascript#es6-template-literals)

### comment.pug

![image](https://user-images.githubusercontent.com/85496220/123504479-4f451a80-d662-11eb-8f46-266323e4e44f.png)

Для подобных мест следует использовать сокращённую запись: `+like-button({ count, isLiked })`

**Comment by misha-yakubchuk** [comment]
> Здесь точно нужна запятая?)

pug в некоторых местах автоматически добавляет запятые
![2](https://user-images.githubusercontent.com/47563274/123512852-77e50880-d692-11eb-9f66-c9e8124425a7.gif)

Я добавлял запятые между атрибутами, потому что мне казалось, что так их проще разделять визуально. Потому что может быть какая нибудь вот такая штука и глаз замыливается(субъективно). 
![image](https://user-images.githubusercontent.com/47563274/123513081-cba42180-d693-11eb-8693-e3f767164d65.png)
![image](https://user-images.githubusercontent.com/47563274/123513167-3f462e80-d694-11eb-9d63-6ee53f7af4bf.png)

А ещё я встретил вот такую вещь в pug, хотя пусть подсветка и меняется, но компилится всё нормально, работает как и прежде.
![3](https://user-images.githubusercontent.com/47563274/123513119-eaa2b380-d693-11eb-9b06-4e468e3ae7a5.gif)


Хотя в html между атрибутами запятых нет. Удалять ВСЕ запятые между атрибутами?

**Comment by romansilivestrov** [comment]
>Я добавлял запятые между атрибутами, потому что мне казалось, что так их проще разделять визуально. Потому что может быть какая нибудь вот такая штука и глаз замыливается(субъективно).
>Удалять ВСЕ запятые между атрибутами?

Да не, пусть будет, если работает.
