### ISSUE TITLE
Локальная сборка проекта

### ISSUE THREAD

**Issue by romansilivestrov** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#14]
У меня локально ни один скрипт не запускается:
![image](https://user-images.githubusercontent.com/85496220/122113378-b2e17380-ce2a-11eb-9fdd-716886adbe25.png)

Проблема в названии папки `ui-kit` - линух и мак в отличие от винды чувствительны к регистру имён. И это не единственная такая директория.

При исправлении появляется новая ошибка (скрипт `start` - не подгружаются шрифты):

![image](https://user-images.githubusercontent.com/85496220/122115639-5f245980-ce2d-11eb-9f5c-749adce59e33.png)
![image](https://user-images.githubusercontent.com/85496220/122115874-9561d900-ce2d-11eb-90de-32e78fb6eb65.png)

**Comment by misha-yakubchuk** [comment]
1) Не могу понять, а в чём проблема с папкой ui-kit? Название папки в нижнем регистре, в webpack.config тоже указана в нижнем регистре. Проверил, что возвращает createEntryPoints(), вроде всё совпадает с названиями папок и файлов. К сожалению ни мака, ни линукса у меня нет, нет возможности потестить. 
![image](https://user-images.githubusercontent.com/47563274/122270812-5f812b00-cee7-11eb-9c04-4c076999cab5.png)

2) Там каким-то чудом затисался material`I`cons-regular.woff2. Что интересно, когда меняю название на material`i`cons-regular.woff2 гит не видит разницы, то есть добавлять в индекс мне нечего. Как в таком случае правильней поступить? Удалить, закоммитить, добавить с нормальным названием, закоммитить?

**Comment by misha-yakubchuk** [comment]
Я нашёл....оказывается на гитхабе лежит в другом регистре..при том, что у меня локально уже давно в нижнем регистре. Я даже не знал. 
![image](https://user-images.githubusercontent.com/47563274/122271315-f1893380-cee7-11eb-840d-e347e52bf876.png)
![image](https://user-images.githubusercontent.com/47563274/122271352-f9e16e80-cee7-11eb-9fe5-1d75a37468a0.png)

**Comment by misha-yakubchuk** [comment]
Вроде бы сейчас должно работать.
