### ISSUE TITLE
Неточности вёрстки

### ISSUE THREAD

**Issue by Everrest1** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#16]
У содержимого кликабельных элементов не должно быть возможности попадать в выделение

![image](https://user-images.githubusercontent.com/43137324/126512320-851b0524-06e8-40b2-9c61-fb8519444d29.png)

Элементы внутри "съезжают" вверх и влево на пару пикселей после раскрытия шторки
Символы "+" и "-" расположены не по центру кнопки

![Peek 2021-07-21 18-09](https://user-images.githubusercontent.com/43137324/126512796-1f6c8e77-2632-49e8-b253-535376182653.gif)

Ширина кнопки лайка изменяется при клике

![Peek 2021-07-21 18-12](https://user-images.githubusercontent.com/43137324/126513339-a135ddd2-87bf-47e1-acae-778eaef55e1d.gif)

Формат ввода даты не соответствует макету

![image](https://user-images.githubusercontent.com/43137324/126514072-ff5454d6-45f5-4a0b-bc56-a664199a3c64.png)
![image](https://user-images.githubusercontent.com/43137324/126514141-11b2e3af-b66d-488c-a376-5823c873b196.png)

В макете нет сноски

![image](https://user-images.githubusercontent.com/43137324/126514863-64311136-b476-4ef4-8605-c73beda5ee6c.png)
![image](https://user-images.githubusercontent.com/43137324/126514735-d2567198-b7f9-4621-b13a-a1865e000bfa.png)

На странице cards у календаря почему-то другие стрелочки

![image](https://user-images.githubusercontent.com/43137324/126515026-0945243f-ccaa-45cb-95cb-17a972dcba59.png)

Календарь не должен вылезать за ширину инпута

![image](https://user-images.githubusercontent.com/43137324/126515389-3d8439df-5241-4cd5-8718-cf478c7656f4.png)

В макете ширина линии 1px

![image](https://user-images.githubusercontent.com/43137324/126515899-dee976ae-d1a9-472d-93b1-47272356a35d.png)

**Comment by misha-yakubchuk** [comment]
> Формат ввода даты не соответствует макету

А где ты нашёл это? У меня точки везде. Проверил хромиум и фаерфокс.
![image](https://user-images.githubusercontent.com/47563274/126523804-88d798f8-1102-4ea4-9f07-9f6d99463c08.png)

**Comment by misha-yakubchuk** [comment]
> На странице cards у календаря почему-то другие стрелочки

Потому что стрелочки меняются через js, когда календарь инициализируется на инпутах. В cards же он просто статический, добавляется в html через класс `datepicker-here`, на который плагин автоматически подтягивается. И в таком виде существует только на странице cards.

**Comment by Everrest1** [comment]
> Потому что стрелочки меняются через js, когда календарь инициализируется на инпутах. В cards же он просто статический, добавляется в html через класс `datepicker-here`, на который плагин автоматически подтягивается. И в таком виде существует только на странице cards.

Нужно сделать, как в макете)

**Comment by Everrest1** [comment]
Ещё тут можно убрать выделение

![image](https://user-images.githubusercontent.com/43137324/126806352-16c7e16b-de61-4677-8ff7-f4578deaf235.png)
