### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Everrest1** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#17]
Класс одного блока внутри другого

![image](https://user-images.githubusercontent.com/43137324/126517580-4ec0d0a8-ff47-459e-9f5a-aa466968d021.png)

> Модификатор — должен удовлетворять свойствам модификатора из английского языка. Всегда adjective или adjectival phrase

[п.4.1](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![image](https://user-images.githubusercontent.com/43137324/126517716-b9c9b69d-f349-4c93-af09-32aaa7fbf8c5.png)

Блоки не должны знать детали реализации других блоков, здесь блок использует классы других

![image](https://user-images.githubusercontent.com/43137324/126518085-caf53520-d40c-49fe-b553-42a6b8b996c3.png)
![image](https://user-images.githubusercontent.com/43137324/126520000-71b1f3fd-99fd-4b7b-b675-8ba4bbd191d3.png)

Использование миксов запрещено [правилами](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.5)

![image](https://user-images.githubusercontent.com/43137324/126518627-6253f536-7e9d-4b5f-9831-450b96b97902.png)
![image](https://user-images.githubusercontent.com/43137324/126519576-1a4d1980-c1ee-49cd-a9fe-e44bf04f14b3.png)

У всех блоков должен быть pug миксин

![image](https://user-images.githubusercontent.com/43137324/126519871-7276728d-57b8-4cda-a8e4-8e23a452c39b.png)

**Comment by misha-yakubchuk** [comment]
> У всех блоков должен быть pug миксин

Это не то что бы прям блок...скорее файлы календаря, которые надо подключать в место использования календаря.

**Comment by Everrest1** [comment]
Из [методологии](https://ru.bem.info/methodology/block-modification/#%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%BC) БЭМ 

![image](https://user-images.githubusercontent.com/43137324/126802078-8e2fc346-41f7-43af-86b8-c8694e37b84a.png)

Соответственно модификаторы по типу `_place_somewhere` не совсем верны

**Comment by Everrest1** [comment]
> > У всех блоков должен быть pug миксин
> 
> Это не то что бы прям блок...скорее файлы календаря, которые надо подключать в место использования календаря.

Что значит 'файлы календаря'?) Как другой разработчик должен догадаться, что файлы календаря находятся в папке другого блока?) А сейчас он оформлен именно как отдельный блок

![image](https://user-images.githubusercontent.com/43137324/126802540-8901ed5c-71ad-4118-ad69-d4e409d847a5.png)

**Comment by Everrest1** [comment]
У тебя часто встречается модификатор '_type_smth', который не отвечает на вопрос какое свойство у этого элемента было изменено, а скорее говорит о том чем является этот элемент

![image](https://user-images.githubusercontent.com/43137324/126804791-7df6f98e-edc5-484a-96a5-fd7f0cda67fd.png)

![image](https://user-images.githubusercontent.com/43137324/126804946-6d274e95-3e55-4d00-8ad0-2ee7aea6dfca.png)

**Comment by misha-yakubchuk** [comment]
> Что значит 'файлы календаря'?) Как другой разработчик должен догадаться, что файлы календаря находятся в папке другого блока?) А сейчас он оформлен именно как отдельный блок

Тогда возможно будет правильней вынести папку `calendar `из папки `components`? Создать например папку `plugins`. То есть это не блок, это файлы плагина которые надо подключить в место использования плагина. В моём случае это блоки `filter-date` и `date-dropdown`.

**Comment by Everrest1** [comment]
Ещё микс остался

![image](https://user-images.githubusercontent.com/43137324/127186288-f0d4e0fa-5232-4e53-820e-9dc2724bb018.png)

**Comment by Everrest1** [comment]
Как вариант, можно использовать data-атрибуты для хранения такой информации

![image](https://user-images.githubusercontent.com/43137324/127643210-f4a5aec8-c1f2-4474-868c-7be8dc174036.png)

**Comment by Everrest1** [comment]
Блок внутри другого блока

![image](https://user-images.githubusercontent.com/43137324/127810957-3261153d-c654-49d1-822f-a6b6602627a4.png)

**Comment by Everrest1** [comment]
Видимо старый код остался

![image](https://user-images.githubusercontent.com/43137324/128296830-7caff81d-aa62-449d-81a0-09462ad8431b.png)

![image](https://user-images.githubusercontent.com/43137324/128296774-805eea52-eaf3-462c-9201-ceb7f911f286.png)
