### ISSUE TITLE
Динамическое заполнение массива

### ISSUE THREAD

**Issue by Everrest1** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#18]
Этот код можно переписать пользуясь методами `map`, сократив число массивов до двух, если элементами использовать объект, например
`
{
  pageName: ...
  pageDir: ...
  entryPoint: ...
}
`

![image](https://user-images.githubusercontent.com/43137324/126520653-144e3fe5-6e7e-4218-b413-685ca1d6fafb.png)

Тут можно тоже сделать похожим образом
Почему не использовать латеральную инициализацию объекта params?

![image](https://user-images.githubusercontent.com/43137324/126521215-f55d9213-70ca-4b55-9743-8fc55ba98688.png)

**Comment by misha-yakubchuk** [comment]
> Тут можно тоже сделать похожим образом

Немного не понял о чём речь. Здесь просто для каждого dropdownElement назначается логика. 
Литеральную инициализацию сделал.

**Comment by Everrest1** [comment]
Можно ещё немного улучшить, вынести заполнение массива pages из функции, сохранить результат поиска и обработки uikit и webPages в разные переменные, а массив pages будет результатом их конкатенации. Таким образом, избавляемся от let и сайд эффектов в функции, а createEntryPoints лучше сделать не стрелочной, а обычной function definition, которая будет принимать массив и возвращать нужный объект. Само преобразование, кстати, можно переписать используя метод Object.fromEntries))

![image](https://user-images.githubusercontent.com/43137324/126799624-fddfd4d9-ecc2-4f06-b63e-b5fc3d06717f.png)
