### ISSUE TITLE
Perfect pixel

### ISSUE THREAD

**Issue by Everrest1** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#21]
Добавь плиз в папку с проектом скрины по которым ты сверял perfect pixel и настройки плагина

**Comment by misha-yakubchuk** [comment]
> настройки плагина

Я пользовался браузерным расширением, настройки расширения не менял.
![image](https://user-images.githubusercontent.com/47563274/126811675-e39ba3e1-5b3b-4eb0-915f-00423da5428d.png)

**Comment by Everrest1** [comment]
Цвет текста темнее, чем в макете

![image](https://user-images.githubusercontent.com/43137324/127813254-bf25a8d1-88b3-4b52-b573-f19fd61d2953.png)

А тут светлее

![image](https://user-images.githubusercontent.com/43137324/127813403-9fcf9217-1bb0-430f-b930-c7ba7a951557.png)

Размер календаря не сошёлся и карточки съехали вниз

![image](https://user-images.githubusercontent.com/43137324/127813958-53443c7b-441d-47b3-8ab5-dc854bdc42d7.png)

**Comment by misha-yakubchuk** [comment]
> А тут светлее

Из макета непонятно, это placeholder или уже выбранное значение. Я сделал по аналогии с другими полями. Placeholder с прозрачностью 0.25, выбранное значение с прозрачностью 0.75.

> Размер календаря не сошёлся и карточки съехали вниз

Это от месяца зависит) Если вернуться на Июль, календарь станет больше и карточки станут на место. Здесь же статичный календарь, не привязанный ни к какому инпуту, а следовательно без position: absolute, без кнопок и бесполезный)
