### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by Everrest1** [FanManutd/The-2nd-task-by-Misha-Yakubchuk#27]
Сейчас многие комментарии в коде излишни

Например, это должно быть понятно из имени свойства

![image](https://user-images.githubusercontent.com/43137324/127812474-2c557481-ab18-42bb-8853-821476aa4bdd.png)

Тут можно и так понять, что делает данное выражение по самому коду

![image](https://user-images.githubusercontent.com/43137324/127812546-3bbb56a4-dae8-4ea0-9209-99efef853267.png)
![image](https://user-images.githubusercontent.com/43137324/127812573-f785bae8-47da-4b50-a075-dd949de0ffc1.png)
![image](https://user-images.githubusercontent.com/43137324/127812622-4196e924-9749-478c-bd0c-86c6af805fb7.png)

В общем, комментарии используются только для того, чтобы указать на совсем не очевидные вещи, у тебя таких вроде бы нет. Смысл в том, что код должен быть написан так, чтобы его можно было понять и разобраться без комментариев.

**Comment by misha-yakubchuk** [comment]
Оставил комментарии в pug, где могут приниматься сложные параметры в миксин. так как pug не позволяет описывать, что необходимо передать в миксин.

**Comment by Everrest1** [comment]
> Оставил комментарии в pug, где могут приниматься сложные параметры в миксин. так как pug не позволяет описывать, что необходимо передать в миксин.

Ты можешь указать значения по-умолчанию, это и будут примеры
